# fly.toml app configuration file generated for bangui-finance on 2024-10-17T11:17:48-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bangui-finance'
primary_region = 'ewr'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
