app = 'bangui-finance'
primary_region = 'ewr'

[http_service]
  internal_port = 3000  # Update this to match your Rails server
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
