# config/secrets.yml
development:
  orange_money_client_id: <%= ENV["ORANGE_MONEY_CLIENT_ID"] %>
  orange_money_client_secret: <%= ENV["ORANGE_MONEY_CLIENT_SECRET"] %>

production:
  orange_money_client_id: <%= ENV["ORANGE_MONEY_CLIENT_ID"] %>
  orange_money_client_secret: <%= ENV["ORANGE_MONEY_CLIENT_SECRET"] %>
