source "https://rubygems.org"

ruby "3.2.0"

gem "rails", "~> 7.1.4"
gem "pg"
gem "puma", ">= 5.0"
gem "bootsnap", require: false
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Authentication & Authorization
gem "devise", "~> 4.9"
gem "devise-jwt", "~> 0.12.1"
gem "jwt"
gem "jwt_sessions", '~> 2.6'
gem "bcrypt", '~> 3.1.7'

# API & CORS
gem "rack-cors", "~> 2.0"

# Communications
gem 'twilio-ruby'
gem 'sendgrid-ruby'

# Frontend & Assets
gem "tailwindcss-rails"
gem "jsbundling-rails"
# Development tools
group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem "pry"
end

group :development do
  gem 'foreman'
  gem "dockerfile-rails", ">= 1.6"
end