name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Fly CLI
        run: curl -sSL https://fly.io/install.sh | sh

      - name: Deploy
        run: |
          fly deploy
        env:
          FLY_API_TOKEN: FlyV1 fm2_lJPECAAAAAAAB7xExBB8pDuqxgf5y7SKtEdPgr9WwrVodHRwczovL2FwaS5mbHkuaW8vdjGWAJLOAAzhih8Lk7lodHRwczovL2FwaS5mbHkuaW8vYWFhL3YxxDzpEM/I9Gn82T17CBHXwe9DUsUyoH8K/Q/QAp/wuxo6yrqkbsYc+iDQU8rIvZiwkXtwM76eT1dy+0oIxujETsUxW9WLq/qRl1i7UrUF2PDiSg8AGJOiMwAgzD93RDCdPdEyAhOkACbYvYn2AZR/CWRIsnEPsqksXrEybAuJOHkUOP/PPKPqu5xGbMg74g2SlAORgc4AS2hyHwWRgqdidWlsZGVyH6J3Zx8BxCDCoHRIQLyIAB7LRQLXOPj+y2dLxJVIEyc29LXmor7PBA==,fm2_lJPETsUxW9WLq/qRl1i7UrUF2PDiSg8AGJOiMwAgzD93RDCdPdEyAhOkACbYvYn2AZR/CWRIsnEPsqksXrEybAuJOHkUOP/PPKPqu5xGbMg74sQQIuZ/vqpRgUr1+dwURrsDK8O5aHR0cHM6Ly9hcGkuZmx5LmlvL2FhYS92MZgEks5nEaZszwAAAAEjCcSKF84ADHy0CpHOAAx8tAzEEK2fm5Mf7hMeUUmCMeKJ8ULEILSkj7b9vJFQ94/3GKULbOS/8SpXUsvgPo/LBplSdGO+

